#!/usr/bin/env node

const path = require('path');

require('dotenv').config({ silent: true, path: path.join(__dirname, '.env') });

const Controller = require("./lib").Controller;
const controller = new Controller({ wsURL: process.env.WSS_URL });
